background_opacity 0.7
dynamic_background_opacity yes

cursor_blink_interval 0
cursor_trail 1

foreground   #ce9e97
background   #0c0302
cursor       #ce9e97

color0       #0c0302
color8       #906e69
color1       #744539
color9       #744539
color2       #774946
color10      #774946
color3       #98261B
color11      #98261B
color4       #DD3222
color12      #DD3222
color5       #F24F34
color13      #F24F34
color6       #9A5A52
color14      #9A5A52
color7       #ce9e97
color15      #ce9e97

font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic
