background {
    monitor = DP-3
    path = screenshot
    blur_passes = 4
    blur_size = 6
    brightness = 0.80
    contrast = 0.9
    vibrancy = 0.2
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%A, %d %B')</span>"
    color = rgba(ce9e97ff)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%I:%M %p')</span>"
    color = rgba(ce9e97ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    size = 320, 52
    position = 0, -120
    halign = center
    valign = center

    outline_thickness = 2
    outer_color = rgba(9A5A52ff)
    inner_color = rgba(0c0302cc)
    font_color = rgba(ce9e97ff)
    check_color = rgba(906e69ff)
    fail_color = rgba(744539ff)
    caps_lock_color = rgba(98261Bff)

    placeholder_text = <i>enter password...</i>
    hide_input = false
    rounding = 6

    fade_on_empty = true
    fade_timeout = 1000
}
